### ISSUE TITLE
Add MPI options command line arguments configuration

### ISSUE THREAD

**Issue by csepanda** [csepanda/qm#1]
Currently MPI can be configured only via simulation configuration
```
simulationConfiguration:
    networkStack: linux
    stopTime: 800s
    enableMpi: true
    systemIdMarkerStrategy: manual
```

It will be nice to have following command line arguments for MPI configuration:
MPI modeling enabling: `--enable-mpi`
SystemIdMarkerStrategy specifying: `--system-id-marker-strategy=<strategy_name>`
