### ISSUE TITLE
Model YAML Configuration: Application's arguments via scalar string

### ISSUE THREAD

**Issue by csepanda** [csepanda/qm#2]
Currently application's arguments are passed via YAML sequence:
```
    - binary: ip
      node: !Ref node04
      arguments:
          - route
          - add
          - default
          - via
          - 10.0.2.1
          - dev
          - sim0
      startAt: 15s
```

It will be nice to have ability to specify arguments via scalar string:
```
    - binary: ip
      node: !Ref node04
      arguments: route add default via 10.0.2.1 dev sim0
      startAt: 15s
```
